name: Go

on: ["push", "pull_request"]

jobs:
  build_yakit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ github.ref }}
      - uses: papeloto/action-zip@v1
        with:
          files: yak_mitm yak_module yak_nmap ./sources.json
          recursive: false
          dest: yakit-resources.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: yakit-resources.zip
          path: ./yakit-resources.zip
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: yakit-resources.zip
          path: ./yakit-resources.zip
      - name: Upload yakit-store to oss
        uses: tvrcgo/upload-to-oss@master
        with:
          key-id: ${{ secrets.OSS_KEY_ID }}
          key-secret: ${{ secrets.OSS_KEY_SECRET }}
          region: oss-accelerate
          bucket: yaklang
          assets: |
            ./yakit-resources.zip:/yak/yakit-resources.zip
